[general]
live_config_reload = true
import = ["~/.config/alacritty/themes/kanso_zen.toml"]

[env]
TERM = "xterm-256color"
COLORTERM = "truecolor"

[terminal]
shell = "/opt/homebrew/bin/nu"

[window]
decorations = "buttonless"
padding = { x = 8, y = 8 }
blur = true
startup_mode = "Maximized"
dynamic_title = true
dynamic_padding = true
opacity = 1

[font.normal]
family = "JetBrainsMono Nerd Font Mono"
style = "Medium"

[font]
bold = { style = "Bold" }
italic = { style = "Italic" }
size = 18
offset = { x = 0, y = 28 }
glyph_offset = { x = 0, y = 12 }

[cursor]
blink_timeout = 0
unfocused_hollow = false
thickness = 0.2

[cursor.style]
shape = "Block"
blinking = "On"

[mouse]
hide_when_typing = true

[colors]
transparent_background_colors = true
draw_bold_text_with_bright_colors = true

[keyboard]
bindings = [
    { key = "Q", mods = "Command", action = "None" },
    { key = "W", mods = "Command", action = "None" },
]
