add_newline = false

# [character]
# # success_symbol = '[âœ](bold green)'

[git_branch]
symbol = 'ğŸŒ± '

[package]
disabled = true

[nodejs]
disabled = true

[lua]
disabled = true
# format = """
# $git_branch"""
