add_newline = false

# [character]
# # success_symbol = '[âžœ](bold green)'

[git_branch]
symbol = 'ðŸŒ± '

[package]
disabled = true

[nodejs]
disabled = true

[lua]
disabled = true

[golang]
disabled = true

# format = """
# $git_branch"""
