add_newline = false
follow_symlinks = false

[character]
success_symbol = '[â¯](bold green) '
error_symbol = '[âœ—](bold red) '

[git_branch]
symbol = 'ğŸŒ± '

[package]
disabled = true

[nodejs]
disabled = true

[lua]
disabled = true

[golang]
disabled = true

# format = """
# $git_branch"""
